/**
 * 建築家あてクイズのデータ
 *
 * このファイルだけが題材を知っている。engine.js は QUIZ の形しか見ないので、
 * 別のクイズを作るときはこのファイルを差し替えればよい。
 *
 * QUIZ のフィールド
 *   id                 sessionStorage / localStorage のキーに使う識別子
 *   title / lead / prompt / rosterTitle / credit   画面に出す文言
 *   levels             難易度の選択。{ id, label, match(q) }
 *   choicesPerQuestion 1問あたりに並べる選択肢の数。0 なら常に全選択肢を並べる
 *   meta               解答後に出す1行（問題と正解の選択肢を受け取る関数）
 *   grades             [正答率の下限, 称号, ひとこと] を高い順に並べたもの
 *   choices            解答ボタン。{ id, name, sub }。並び順がそのままボタンの順になる
 *   questions          出題。{ id, answer, level, image, title, year, place, note, wiki }
 *
 * level は難易度。1 = 名前を知っていれば当たる代表作、2 = 建築を少し追っていれば
 * 分かるもの、3 = 作風を知らないと当てにくいもの。難易度の選択で絞り込む。
 *
 * 写真について
 *   image を指定するとその URL / 相対パス（例: "images/yoyogi.jpg"）を最優先で使う。
 *   空のままなら wiki.ja → wiki.en の順に Wikipedia の REST API を叩き、
 *   記事の代表画像を取得して出題する。差し替えたい問題だけ image を書けばよい。
 *   記事が無い建築は写真を取得できないが、その問題は予備の問題と自動で
 *   差し替わるので、出題数は保たれる。
 */

const QUIZ = {
  id: 'architect',
  title: '建築家あてクイズ',
  lead: '建築の写真が表示されます。<br>設計した建築家を16人の中から選んでください。',
  prompt: 'この建築を設計したのは？',
  rosterTitle: '出題される建築家',
  credit: '写真は各建築のWikipedia記事の代表画像を実行時に読み込んでいます。著作権は各撮影者に帰属します。',

  choicesPerQuestion: 0,

  levels: [
    { id: 'all',  label: 'すべて',       match: () => true },
    { id: 'mid',  label: '有名作を除く', match: (q) => q.level >= 2 },
    { id: 'deep', label: 'マニア向け',   match: (q) => q.level === 3 },
  ],

  meta: (q, answer) => `${answer.name}／${q.year}／${q.place}`,

  grades: [
    [0.999, '巨匠',     '全問正解。もはや設計者本人では。'],
    [0.8,   '建築通',   'ディテールまでよく見えています。'],
    [0.6,   '愛好家',   '主要作はしっかり押さえています。'],
    [0.4,   '見習い',   '素材と輪郭に注目すると見分けやすくなります。'],
    [0,     '初学者',   'まずは代表作から。もう一周してみましょう。'],
  ],

  choices: [
    { id: 'kuma',      name: '隈研吾',                     sub: '1954–' },
    { id: 'ando',      name: '安藤忠雄',                   sub: '1941–' },
    { id: 'sanaa',     name: 'SANAA',                      sub: '1995–' },
    { id: 'ito',       name: '伊東豊雄',                   sub: '1941–' },
    { id: 'ban',       name: '坂茂',                       sub: '1957–' },
    { id: 'hara',      name: '原広司',                     sub: '1936–' },
    { id: 'naito',     name: '内藤廣',                     sub: '1950–' },
    { id: 'fujimoto',  name: '藤本壮介',                   sub: '1971–' },
    { id: 'maki',      name: '槇文彦',                     sub: '1928–2024' },
    { id: 'tange',     name: '丹下健三',                   sub: '1913–2005' },
    { id: 'kurokawa',  name: '黒川紀章',                   sub: '1934–2007' },
    { id: 'fujimori',  name: '藤森照信',                   sub: '1946–' },
    { id: 'wright',    name: 'フランク・ロイド・ライト',   sub: '1867–1959' },
    { id: 'corbu',     name: 'ル・コルビュジエ',           sub: '1887–1965' },
    { id: 'mies',      name: 'ミース・ファン・デル・ローエ', sub: '1886–1969' },
    { id: 'gaudi',     name: 'アントニ・ガウディ',         sub: '1852–1926' },
  ],

  questions: [
    // ── 隈研吾 ─────────────────────────────────────────
    { id:'kuma-kokuritsu', answer:'kuma', level:1, image:'', title:'国立競技場', year:'2019年', place:'東京都新宿区',
      wiki:{ja:'国立競技場', en:'Japan National Stadium'},
      note:'47都道府県の杉材で庇を編んだ「杜のスタジアム」。木と鉄骨のハイブリッド屋根。' },
    { id:'kuma-nezu', answer:'kuma', level:2, image:'', title:'根津美術館', year:'2009年', place:'東京都港区',
      wiki:{ja:'根津美術館', en:'Nezu Museum'},
      note:'深い大屋根と竹の並ぶアプローチ。表参道の喧噪から庭園へ人を導く。' },
    { id:'kuma-asakusa', answer:'kuma', level:2, image:'', title:'浅草文化観光センター', year:'2012年', place:'東京都台東区',
      wiki:{ja:'浅草文化観光センター', en:'Asakusa Culture Tourist Information Center'},
      note:'平屋の家を8層積み上げたような外観。斜めの屋根がそのまま各階の天井になる。' },
    { id:'kuma-kadokawa', answer:'kuma', level:2, image:'', title:'角川武蔵野ミュージアム', year:'2020年', place:'埼玉県所沢市',
      wiki:{ja:'角川武蔵野ミュージアム', en:'Kadokawa Culture Museum'},
      note:'約2万枚の花崗岩を貼った多面体の巨岩。木や格子を使わない異色作。' },
    { id:'kuma-vad', answer:'kuma', level:2, image:'', title:'V&Aダンディー', year:'2018年', place:'イギリス・ダンディー',
      wiki:{ja:'V&Aダンディー', en:'V&A Dundee'},
      note:'スコットランドの断崖から着想した、水面にせり出す反り返ったコンクリートの塊。' },
    { id:'kuma-takanawa', answer:'kuma', level:2, image:'', title:'高輪ゲートウェイ駅', year:'2020年', place:'東京都港区',
      wiki:{ja:'高輪ゲートウェイ駅', en:'Takanawa Gateway Station'},
      note:'折り紙のような白い膜屋根を、細い集成材の方杖が支える。' },
    { id:'kuma-hiroshige', answer:'kuma', level:3, image:'', title:'那珂川町馬頭広重美術館', year:'2000年', place:'栃木県那珂川町',
      wiki:{ja:'那珂川町馬頭広重美術館', en:'Nakagawa-machi Bato Hiroshige Museum of Art'},
      note:'八溝杉の細いルーバーで全体を覆う。広重の描く雨線を建築に翻訳した初期の代表作。' },
    { id:'kuma-toyama', answer:'kuma', level:3, image:'', title:'富山市ガラス美術館（TOYAMAキラリ）', year:'2015年', place:'富山県富山市',
      wiki:{ja:'富山市ガラス美術館', en:'Toyama Glass Art Museum'},
      note:'御影石・ガラス・アルミの斜めのファサード。内部は県産杉のルーバーが吹き抜けを貫く。' },
    { id:'kuma-aore', answer:'kuma', level:3, image:'', title:'アオーレ長岡', year:'2012年', place:'新潟県長岡市',
      wiki:{ja:'アオーレ長岡', en:'Aore Nagaoka'},
      note:'市役所とアリーナの間に屋根付き広場「ナカドマ」を挟む。越後杉の乱張りが目印。' },
    { id:'kuma-suntory', answer:'kuma', level:3, image:'', title:'サントリー美術館', year:'2007年', place:'東京都港区',
      wiki:{ja:'サントリー美術館', en:'Suntory Museum of Art'},
      note:'白磁のような外装と、館内に多用された白い木格子。「都市の中の生活空間」を掲げた。' },
    { id:'kuma-shinpuhkan', answer:'kuma', level:3, image:'', title:'新風館', year:'2020年', place:'京都府京都市',
      wiki:{ja:'新風館', en:'Shinpuhkan'},
      note:'大正期の旧京都中央電話局を保存しつつ、低く抑えた瓦と木の新棟を絡ませた。' },
    { id:'kuma-tokorozawa', answer:'kuma', level:3, image:'', title:'ところざわサクラタウン', year:'2020年', place:'埼玉県所沢市',
      wiki:{ja:'ところざわサクラタウン', en:'Tokorozawa Sakura Town'},
      note:'岩の塊のようなミュージアムを中心に、神社や書店を散りばめた複合施設。' },

    // ── 安藤忠雄 ───────────────────────────────────────
    { id:'ando-hikari', answer:'ando', level:1, image:'', title:'光の教会', year:'1989年', place:'大阪府茨木市',
      wiki:{ja:'茨木春日丘教会', en:'Church of the Light'},
      note:'コンクリートの箱の正面に穿たれた十字のスリット。開口そのものが祭壇となる。' },
    { id:'ando-chichu', answer:'ando', level:1, image:'', title:'地中美術館', year:'2004年', place:'香川県直島町',
      wiki:{ja:'地中美術館', en:'Chichu Art Museum'},
      note:'景観を守るため大半を地中に埋め、三角形や正方形の中庭から自然光だけを落とす。' },
    { id:'ando-omotesando', answer:'ando', level:2, image:'', title:'表参道ヒルズ', year:'2006年', place:'東京都渋谷区',
      wiki:{ja:'表参道ヒルズ', en:'Omotesando Hills'},
      note:'ケヤキ並木に合わせて高さを抑え、内部は参道と同じ勾配のスロープが巡る。' },
    { id:'ando-sumiyoshi', answer:'ando', level:2, image:'', title:'住吉の長屋', year:'1976年', place:'大阪府大阪市',
      wiki:{ja:'住吉の長屋', en:'Row House in Sumiyoshi'},
      note:'間口2間の長屋を3分割し、中央を屋根のない中庭に。移動には傘が要る。' },
    { id:'ando-mizu', answer:'ando', level:2, image:'', title:'水の教会', year:'1988年', place:'北海道占冠村',
      wiki:{ja:'水の教会', en:'Church on the Water'},
      note:'人工池に十字架を立て、正面のガラス壁が丸ごと開く。教会三部作のひとつ。' },
    { id:'ando-awaji', answer:'ando', level:3, image:'', title:'淡路夢舞台', year:'2000年', place:'兵庫県淡路市',
      wiki:{ja:'淡路夢舞台', en:'Awaji Yumebutai'},
      note:'埋め立てで削られた山肌の再生。100個の正方形花壇が斜面に並ぶ「百段苑」。' },
    { id:'ando-hyogo', answer:'ando', level:3, image:'', title:'兵庫県立美術館', year:'2002年', place:'兵庫県神戸市',
      wiki:{ja:'兵庫県立美術館', en:'Hyogo Prefectural Museum of Art'},
      note:'海に面した細長い箱に、円筒の階段室と巨大な野外階段が取り付く。' },
    { id:'ando-chikatsu', answer:'ando', level:3, image:'', title:'大阪府立近つ飛鳥博物館', year:'1994年', place:'大阪府河南町',
      wiki:{ja:'大阪府立近つ飛鳥博物館', en:'Osaka Prefectural Chikatsu Asuka Museum'},
      note:'屋根全体が巨大な階段状の広場。古墳の上に登るように建物を歩ける。' },
    { id:'ando-shiba', answer:'ando', level:3, image:'', title:'司馬遼太郎記念館', year:'2001年', place:'大阪府東大阪市',
      wiki:{ja:'司馬遼太郎記念館', en:'Shiba Ryotaro Memorial Museum'},
      note:'高さ11mの弧を描く大書架。曲面のコンクリート壁が自邸の庭を抱き込む。' },
    { id:'ando-benesse', answer:'ando', level:3, image:'', title:'ベネッセハウス', year:'1992年', place:'香川県直島町',
      wiki:{ja:'ベネッセハウス', en:'Benesse House'},
      note:'直島の起点となった美術館とホテルの一体施設。斜面に沿って円と直線が絡む。' },
    { id:'ando-dogana', answer:'ando', level:3, image:'', title:'プンタ・デラ・ドガーナ', year:'2009年', place:'イタリア・ヴェネツィア',
      wiki:{ja:'プンタ・デラ・ドガーナ', en:'Punta della Dogana'},
      note:'17世紀の税関倉庫の中に、コンクリートの箱を入れ子にして挿入した改修。' },
    { id:'ando-kodomo', answer:'ando', level:3, image:'', title:'こども本の森 中之島', year:'2020年', place:'大阪府大阪市',
      wiki:{ja:'こども本の森 中之島', en:'Nakanoshima Children’s Book Forest'},
      note:'壁一面を天井まで本で埋めた吹き抜け。私財を投じて建て、市に寄贈した。' },
    { id:'ando-sayamaike', answer:'ando', level:3, image:'', title:'大阪府立狭山池博物館', year:'2001年', place:'大阪府大阪狭山市',
      wiki:{ja:'大阪府立狭山池博物館', en:'Osaka Prefectural Sayamaike Museum'},
      note:'高さ15mの人工滝が来館者を迎える。日本最古のため池の堤を移築展示する。' },

    // ── SANAA ─────────────────────────────────────────
    { id:'sanaa-kanazawa', answer:'sanaa', level:1, image:'', title:'金沢21世紀美術館', year:'2004年', place:'石川県金沢市',
      wiki:{ja:'金沢21世紀美術館', en:'21st Century Museum of Contemporary Art, Kanazawa'},
      note:'正面のない円形のガラス平屋。どこからでも入れる「まちに開かれた公園のような美術館」。' },
    { id:'sanaa-rolex', answer:'sanaa', level:2, image:'', title:'ロレックス・ラーニングセンター', year:'2010年', place:'スイス・ローザンヌ',
      wiki:{ja:'ロレックス・ラーニングセンター', en:'Rolex Learning Center'},
      note:'床と屋根が一体で波打つ一枚のスラブ。壁で仕切らず、地形の起伏で場所を分ける。' },
    { id:'sanaa-lens', answer:'sanaa', level:2, image:'', title:'ルーヴル・ランス', year:'2012年', place:'フランス・ランス',
      wiki:{ja:'ルーヴル・ランス', en:'Louvre-Lens'},
      note:'炭鉱跡地に置かれた、アルミで鈍く風景を映す低層の列。周囲が壁面に溶ける。' },
    { id:'sanaa-newmuseum', answer:'sanaa', level:3, image:'', title:'ニューミュージアム', year:'2007年', place:'アメリカ・ニューヨーク',
      wiki:{ja:'ニューミュージアム', en:'New Museum'},
      note:'白いアルミメッシュの箱を少しずつずらして積む。ずれた分が天窓になる。' },
    { id:'sanaa-zollverein', answer:'sanaa', level:3, image:'', title:'ツォルフェアアイン・スクール', year:'2006年', place:'ドイツ・エッセン',
      wiki:{ja:'ツォルフェアアイン炭鉱業遺産群', en:'Zollverein School of Management and Design'},
      note:'一辺35mのコンクリートの立方体に、大小の正方形窓を不規則に散らす。' },
    { id:'sanaa-grace', answer:'sanaa', level:3, image:'', title:'グレイス・ファームズ', year:'2015年', place:'アメリカ・コネチカット州',
      wiki:{ja:'', en:'Grace Farms'},
      note:'細長い屋根が丘の斜面を蛇行して下り、その下に5つの機能がぶら下がる。' },
    { id:'sanaa-vitra', answer:'sanaa', level:3, image:'', title:'ヴィトラ・キャンパス 工場棟', year:'2012年', place:'ドイツ・ヴァイル・アム・ライン',
      wiki:{ja:'ヴィトラ・キャンパス', en:'Vitra Campus'},
      note:'直径160mの円形の工場。白いアクリルのカーテンで全周を覆う。' },
    { id:'sanaa-naoshima', answer:'sanaa', level:3, image:'', title:'海の駅なおしま', year:'2006年', place:'香川県直島町',
      wiki:{ja:'宮浦港', en:'Naoshima'},
      note:'細い柱だけで支えた薄い大屋根とガラスの箱。港と待合が地続きになる。' },
    { id:'sanaa-sydney', answer:'sanaa', level:3, image:'', title:'シドニー・モダン・プロジェクト', year:'2022年', place:'オーストラリア・シドニー',
      wiki:{ja:'', en:'Art Gallery of New South Wales'},
      note:'ガラスの箱を段々に重ねて斜面を下り、旧・第二次大戦の石油タンクへ接続する。' },

    // ── 伊東豊雄 ───────────────────────────────────────
    { id:'ito-sendai', answer:'ito', level:1, image:'', title:'せんだいメディアテーク', year:'2001年', place:'宮城県仙台市',
      wiki:{ja:'せんだいメディアテーク', en:'Sendai Mediatheque'},
      note:'13本のねじれたチューブが床を支える。柱・壁・設備を一体化した「海藻」の構造。' },
    { id:'ito-taichung', answer:'ito', level:2, image:'', title:'台中国家歌劇院', year:'2016年', place:'台湾・台中市',
      wiki:{ja:'台中国家歌劇院', en:'National Taichung Theater'},
      note:'直線の柱梁を持たない「洞窟」。曲面の壁が連続して内外をつなぐ。' },
    { id:'ito-tama', answer:'ito', level:2, image:'', title:'多摩美術大学図書館', year:'2007年', place:'東京都八王子市',
      wiki:{ja:'', en:'Tama Art University Library'},
      note:'鉄板とコンクリートの薄いアーチが交差し、床の傾斜がそのまま地面につながる。' },
    { id:'ito-gifu', answer:'ito', level:3, image:'', title:'みんなの森 ぎふメディアコスモス', year:'2015年', place:'岐阜県岐阜市',
      wiki:{ja:'みんなの森 ぎふメディアコスモス', en:'Gifu Media Cosmos'},
      note:'ヒノキの格子屋根から、ポリエステルの「グローブ」が11個ぶら下がる。' },
    { id:'ito-odate', answer:'ito', level:3, image:'', title:'大館樹海ドーム', year:'1997年', place:'秋田県大館市',
      wiki:{ja:'大館樹海ドーム', en:'Odate Jukai Dome'},
      note:'秋田杉の集成材による木造ドーム。楕円の屋根が地面すれすれまで下りてくる。' },
    { id:'ito-meisou', answer:'ito', level:3, image:'', title:'瞑想の森 市営斎場', year:'2006年', place:'岐阜県各務原市',
      wiki:{ja:'瞑想の森市営斎場', en:'Meiso no Mori Municipal Funeral Hall'},
      note:'厚さを変えながら波打つ白いコンクリートシェル。背後の山並みと呼応する。' },
    { id:'ito-yatsushiro', answer:'ito', level:3, image:'', title:'八代市立博物館 未来の森ミュージアム', year:'1991年', place:'熊本県八代市',
      wiki:{ja:'八代市立博物館未来の森ミュージアム', en:'Yatsushiro Municipal Museum'},
      note:'芝生の丘に半分埋まった収蔵庫の上に、アルミの丸屋根が浮く。くまもとアートポリスの一作。' },
    { id:'ito-matsumoto', answer:'ito', level:3, image:'', title:'まつもと市民芸術館', year:'2004年', place:'長野県松本市',
      wiki:{ja:'まつもと市民芸術館', en:'Matsumoto Performing Arts Centre'},
      note:'通りに沿ってうねるガラス壁に、丸窓が散らばる。客席が街路の上に張り出す。' },
    { id:'ito-za', answer:'ito', level:3, image:'', title:'座・高円寺', year:'2009年', place:'東京都杉並区',
      wiki:{ja:'座・高円寺', en:'Za-Koenji Public Theatre'},
      note:'黒いテントを思わせる折れ曲がった外形に、無数の丸い窓を穿つ。' },
    { id:'ito-omishima', answer:'ito', level:3, image:'', title:'今治市伊東豊雄建築ミュージアム', year:'2011年', place:'愛媛県今治市',
      wiki:{ja:'今治市伊東豊雄建築ミュージアム', en:'Toyo Ito Museum of Architecture, Imabari'},
      note:'瀬戸内を望む丘に、黒い鋼板の多面体（スティールハット）と自邸の再現が並ぶ。' },
    { id:'ito-silver', answer:'ito', level:3, image:'', title:'シルバーハット', year:'1984年', place:'東京都中野区',
      wiki:{ja:'シルバーハット', en:'Silver Hut'},
      note:'7つのヴォールト屋根を細い鉄骨で架けた自邸。のちに大三島へ移築された。' },

    // ── 坂茂 ──────────────────────────────────────────
    { id:'ban-metz', answer:'ban', level:2, image:'', title:'ポンピドゥー・センター・メス', year:'2010年', place:'フランス・メス',
      wiki:{ja:'ポンピドゥー・センター・メス', en:'Centre Pompidou-Metz'},
      note:'中国の編み笠から着想した六角格子の木造屋根を、テフロン膜で覆う。' },
    { id:'ban-fuji', answer:'ban', level:2, image:'', title:'静岡県富士山世界遺産センター', year:'2017年', place:'静岡県富士宮市',
      wiki:{ja:'静岡県富士山世界遺産センター', en:'Mount Fuji World Heritage Centre'},
      note:'逆さにした富士を格子で組み、水盤に映すと正しい富士の姿が現れる。' },
    { id:'ban-oita', answer:'ban', level:3, image:'', title:'大分県立美術館', year:'2015年', place:'大分県大分市',
      wiki:{ja:'大分県立美術館', en:'Oita Prefectural Art Museum'},
      note:'1階の水平折戸を開けると街路と展示空間が地続きになる。竹編みを想わせる外装。' },
    { id:'ban-paperchurch', answer:'ban', level:3, image:'', title:'紙の教会', year:'1995年', place:'兵庫県神戸市（現・台湾南投県）',
      wiki:{ja:'紙の教会', en:'Paper Church'},
      note:'阪神淡路大震災の仮設教会。58本の紙管を楕円に並べただけの構造。' },
    { id:'ban-hayek', answer:'ban', level:3, image:'', title:'ニコラス・G・ハイエック センター', year:'2007年', place:'東京都中央区',
      wiki:{ja:'ニコラス・G・ハイエック センター', en:'Nicolas G. Hayek Center'},
      note:'1階の前後を全面ガラスシャッターで開放し、7基のショールーム・エレベーターが上下する。' },
    { id:'ban-onagawa', answer:'ban', level:3, image:'', title:'女川駅', year:'2015年', place:'宮城県女川町',
      wiki:{ja:'女川駅', en:'Onagawa Station'},
      note:'ウミネコが羽ばたく姿を模した木造の大屋根。駅と温泉施設が一体になる。' },
    { id:'ban-aspen', answer:'ban', level:3, image:'', title:'アスペン美術館', year:'2014年', place:'アメリカ・コロラド州',
      wiki:{ja:'', en:'Aspen Art Museum'},
      note:'木質複合材を編んだスクリーンで箱を包む。屋上から下りながら見る順路。' },
    { id:'ban-cardboard', answer:'ban', level:3, image:'', title:'カードボード・カテドラル', year:'2013年', place:'ニュージーランド・クライストチャーチ',
      wiki:{ja:'', en:'Cardboard Cathedral'},
      note:'地震で崩れた大聖堂の仮設。98本の紙管をA形に組み、正面は三角のステンドグラス。' },
    { id:'ban-seine', answer:'ban', level:3, image:'', title:'ラ・セーヌ・ミュジカル', year:'2017年', place:'フランス・ブローニュ＝ビヤンクール',
      wiki:{ja:'', en:'La Seine Musicale'},
      note:'セーヌ川の中州に置いた卵形。太陽電池を貼った帆が日の動きに合わせて外周を回る。' },
    { id:'ban-tainan', answer:'ban', level:3, image:'', title:'台南市美術館2館', year:'2019年', place:'台湾・台南市',
      wiki:{ja:'台南市美術館', en:'Tainan Art Museum'},
      note:'白い箱を少しずつずらして積み、上を五角形の格子屋根（フラクタル）が覆う。' },
    { id:'ban-toyota', answer:'ban', level:3, image:'', title:'豊田市博物館', year:'2024年', place:'愛知県豊田市',
      wiki:{ja:'豊田市博物館', en:'Toyota Municipal Museum of Art'},
      note:'隣の谷口吉生の美術館に高さを合わせ、細い列柱と木の庇で低く水平に構える。' },

    // ── 原広司 ────────────────────────────────────────
    { id:'hara-umeda', answer:'hara', level:1, image:'', title:'梅田スカイビル', year:'1993年', place:'大阪府大阪市',
      wiki:{ja:'梅田スカイビル', en:'Umeda Sky Building'},
      note:'2棟の超高層を最上部の空中庭園で連結。地上で組んだ橋を吊り上げて架けた。' },
    { id:'hara-kyoto', answer:'hara', level:1, image:'', title:'京都駅ビル', year:'1997年', place:'京都府京都市',
      wiki:{ja:'京都駅', en:'Kyoto Station'},
      note:'全長470mのコンコースを「地上の谷」に見立て、大階段が空へ抜ける。' },
    { id:'hara-sapporo', answer:'hara', level:2, image:'', title:'札幌ドーム', year:'2001年', place:'北海道札幌市',
      wiki:{ja:'札幌ドーム', en:'Sapporo Dome'},
      note:'天然芝のサッカーステージが屋外から丸ごと滑り込む、世界初のホヴァリングステージ。' },
    { id:'hara-tasaki', answer:'hara', level:3, image:'', title:'田崎美術館', year:'1986年', place:'長野県軽井沢町',
      wiki:{ja:'田崎美術館', en:'Tazaki Art Museum'},
      note:'カラマツ林に埋もれる打放しの箱。屋根の上に載る三角の採光塔が並ぶ。' },
    { id:'hara-iida', answer:'hara', level:3, image:'', title:'飯田市美術博物館', year:'1989年', place:'長野県飯田市',
      wiki:{ja:'飯田市美術博物館', en:'Iida City Museum'},
      note:'城跡に建つ。銀色の円錐と直方体を組み合わせ、内部に「都市のような」通路を巡らせる。' },
    { id:'hara-miyagi', answer:'hara', level:3, image:'', title:'宮城県図書館', year:'1998年', place:'宮城県仙台市',
      wiki:{ja:'宮城県図書館', en:'Miyagi Prefectural Library'},
      note:'全長160mの巨大な水平の梁が空中に浮く。「宙に浮く本の器」と呼ばれる。' },
    { id:'hara-yamato', answer:'hara', level:3, image:'', title:'ヤマトインターナショナル', year:'1987年', place:'東京都大田区',
      wiki:{ja:'', en:'Yamato International'},
      note:'アルミパネルの段状の外壁が「都市の丘」を成す。屋上に小さな家々が並ぶ。' },
    { id:'hara-oose', answer:'hara', level:3, image:'', title:'内子町立大瀬中学校', year:'1992年', place:'愛媛県内子町',
      wiki:{ja:'', en:'Ose Junior High School'},
      note:'瓦屋根の小さな棟を集落のように分棟配置。中央に木造の吹き抜けを置く。' },

    // ── 内藤廣 ────────────────────────────────────────
    { id:'naito-kochi', answer:'naito', level:2, image:'', title:'高知駅', year:'2008年', place:'高知県高知市',
      wiki:{ja:'高知駅', en:'Kōchi Station'},
      note:'「くじらドーム」と呼ばれる大断面集成材のアーチが、ホーム全体を一息に覆う。' },
    { id:'naito-umi', answer:'naito', level:3, image:'', title:'鳥羽市立海の博物館', year:'1992年', place:'三重県鳥羽市',
      wiki:{ja:'鳥羽市立海の博物館', en:'Toba Sea-Folk Museum'},
      note:'低予算の制約からプレキャストコンクリートと木のトラスを選択。切妻の棟が並ぶ。' },
    { id:'naito-grandtoit', answer:'naito', level:3, image:'', title:'島根県芸術文化センター グラントワ', year:'2005年', place:'島根県益田市',
      wiki:{ja:'島根県芸術文化センター', en:'Iwami Art Museum'},
      note:'約28万枚の石州瓦で壁と屋根をすべて覆う。中央に大きな芝生の中庭を抱く。' },
    { id:'naito-hyuga', answer:'naito', level:3, image:'', title:'日向市駅', year:'2008年', place:'宮崎県日向市',
      wiki:{ja:'日向市駅', en:'Hyūga-shi Station'},
      note:'飫肥杉の柱列がホームを支える高架駅。木の駅舎という発想を全国に広げた。' },
    { id:'naito-makino', answer:'naito', level:3, image:'', title:'牧野富太郎記念館', year:'1999年', place:'高知県高知市',
      wiki:{ja:'高知県立牧野植物園', en:'Kochi Prefectural Makino Botanical Garden'},
      note:'尾根の地形に沿って湾曲する木造の大屋根。中庭を囲んで回廊が巡る。' },
    { id:'naito-chihiro', answer:'naito', level:3, image:'', title:'安曇野ちひろ美術館', year:'1997年', place:'長野県松川村',
      wiki:{ja:'安曇野ちひろ美術館', en:'Chihiro Art Museum Azumino'},
      note:'北アルプスを背に、切妻の低い棟をいくつも連ねる。木の梁を現しにした天井。' },
    { id:'naito-asahikawa', answer:'naito', level:3, image:'', title:'旭川駅', year:'2011年', place:'北海道旭川市',
      wiki:{ja:'旭川駅', en:'Asahikawa Station'},
      note:'道産カラマツの列柱がコンコースを貫き、忠別川へ向かって全面ガラスで開く。' },
    { id:'naito-toyama', answer:'naito', level:3, image:'', title:'富山県美術館', year:'2017年', place:'富山県富山市',
      wiki:{ja:'富山県美術館', en:'Toyama Prefectural Museum of Art and Design'},
      note:'立山連峰に向けて開くガラスの箱。屋上は佐藤卓の遊具が並ぶ「オノマトペの屋上」。' },
    { id:'naito-tokamachi', answer:'naito', level:3, image:'', title:'十日町情報館', year:'1999年', place:'新潟県十日町市',
      wiki:{ja:'十日町情報館', en:'Tokamachi Information Center'},
      note:'豪雪に耐える無柱の閲覧室。コールテン鋼の壁が雪景色のなかで錆色に沈む。' },
    { id:'naito-kusanagi', answer:'naito', level:3, image:'', title:'静岡県草薙総合運動場体育館（このはなアリーナ）', year:'2015年', place:'静岡県静岡市',
      wiki:{ja:'静岡県草薙総合運動場', en:'Kusanagi Sports Complex'},
      note:'県産ヒノキの集成材を編んだ三角格子のドーム。木造としては国内最大級の無柱空間。' },

    // ── 藤本壮介 ──────────────────────────────────────
    { id:'fujimoto-ring', answer:'fujimoto', level:1, image:'', title:'大屋根リング（大阪・関西万博）', year:'2025年', place:'大阪府大阪市',
      wiki:{ja:'大屋根リング', en:'Grand Ring'},
      note:'周長約2kmの木造リング。貫（ぬき）による伝統的な木組みを現代の大架構に持ち込んだ。' },
    { id:'fujimoto-shiroiya', answer:'fujimoto', level:3, image:'', title:'白井屋ホテル', year:'2020年', place:'群馬県前橋市',
      wiki:{ja:'白井屋ホテル', en:'Shiroiya Hotel'},
      note:'旧旅館の床を抜いて4層の吹き抜けを作り、隣に草に覆われた人工の丘を積む。' },
    { id:'fujimoto-serpentine', answer:'fujimoto', level:3, image:'', title:'サーペンタイン・パビリオン 2013', year:'2013年', place:'イギリス・ロンドン',
      wiki:{ja:'', en:'Serpentine Pavilion'},
      note:'細い白鋼のグリッドを雲のように積層した仮設。境界が曖昧な「あいだ」の空間。' },
    { id:'fujimoto-ota', answer:'fujimoto', level:3, image:'', title:'太田市美術館・図書館', year:'2017年', place:'群馬県太田市',
      wiki:{ja:'太田市美術館・図書館', en:'Art Museum & Library, Ota'},
      note:'5つの箱をずらして積み、その隙間をスロープが巻きつくように登る。' },
    { id:'fujimoto-musabi', answer:'fujimoto', level:3, image:'', title:'武蔵野美術大学 美術館・図書館', year:'2010年', place:'東京都小平市',
      wiki:{ja:'武蔵野美術大学', en:'Musashino Art University'},
      note:'高さ9mの本棚だけで壁を作り、それを渦巻き状に巻いて建物の形にした。' },
    { id:'fujimoto-arbre', answer:'fujimoto', level:3, image:'', title:'ラルブル・ブラン', year:'2019年', place:'フランス・モンペリエ',
      wiki:{ja:'', en:'L’Arbre Blanc'},
      note:'全戸に深いバルコニーを突き出させ、白い木の葉が生い茂るような塔にした。' },
    { id:'fujimoto-makiart', answer:'fujimoto', level:3, image:'', title:'マルホンまきあーとテラス', year:'2021年', place:'宮城県石巻市',
      wiki:{ja:'マルホンまきあーとテラス', en:'Ishinomaki Cultural Center'},
      note:'切妻屋根の小さな家を大小18棟、集落のように寄せ集めて文化施設にした。' },
    { id:'fujimoto-housena', answer:'fujimoto', level:3, image:'', title:'House NA', year:'2011年', place:'東京都杉並区',
      wiki:{ja:'', en:'House NA'},
      note:'21枚の床を少しずつ高さをずらして重ねた、白い骨組みだけの透明な住宅。' },
    { id:'fujimoto-budapest', answer:'fujimoto', level:3, image:'', title:'ハンガリー音楽の家', year:'2022年', place:'ハンガリー・ブダペスト',
      wiki:{ja:'', en:'House of Music Hungary'},
      note:'森の木漏れ日を思わせる、100個近い穴の開いた薄い屋根が公園の樹冠に紛れる。' },

    // ── 槇文彦 ────────────────────────────────────────
    { id:'maki-makuhari', answer:'maki', level:2, image:'', title:'幕張メッセ', year:'1989年', place:'千葉県千葉市',
      wiki:{ja:'幕張メッセ', en:'Makuhari Messe'},
      note:'緩やかに湾曲した金属の大屋根が連なる。巨大施設をあくまで軽やかに見せる。' },
    { id:'maki-taiikukan', answer:'maki', level:2, image:'', title:'東京体育館', year:'1990年', place:'東京都渋谷区',
      wiki:{ja:'東京体育館', en:'Tokyo Metropolitan Gymnasium'},
      note:'兜のようなステンレスの屋根。ボリュームの多くを地下に沈め、街に低く構える。' },
    { id:'maki-hillside', answer:'maki', level:2, image:'', title:'ヒルサイドテラス', year:'1969–1998年', place:'東京都渋谷区',
      wiki:{ja:'ヒルサイドテラス', en:'Hillside Terrace'},
      note:'約30年かけて7期に分けて建てた低層の街並み。旧山手通りの表情そのものを作った。' },
    { id:'maki-spiral', answer:'maki', level:3, image:'', title:'スパイラル', year:'1985年', place:'東京都港区',
      wiki:{ja:'スパイラル (建築物)', en:'Spiral (building)'},
      note:'円錐・円筒・格子を非対称にコラージュした正面。内部は螺旋スロープが上昇する。' },
    { id:'maki-4wtc', answer:'maki', level:3, image:'', title:'4 ワールドトレードセンター', year:'2013年', place:'アメリカ・ニューヨーク',
      wiki:{ja:'4 ワールドトレードセンター', en:'4 World Trade Center'},
      note:'装飾を排したミニマルなガラスの角柱。空を映して姿を消すことを目指した。' },
    { id:'maki-kyoto', answer:'maki', level:3, image:'', title:'京都国立近代美術館', year:'1986年', place:'京都府京都市',
      wiki:{ja:'京都国立近代美術館', en:'National Museum of Modern Art, Kyoto'},
      note:'平安神宮の大鳥居に向き合う。格子状に分割した石とガラスの端正な正面。' },
    { id:'maki-toyoda', answer:'maki', level:3, image:'', title:'名古屋大学 豊田講堂', year:'1960年', place:'愛知県名古屋市',
      wiki:{ja:'豊田講堂', en:'Toyoda Auditorium'},
      note:'帰国後まもない30代の作。打放しの壁が跳ね上がるように前へ突き出す。' },
    { id:'maki-kazenooka', answer:'maki', level:3, image:'', title:'風の丘葬斎場', year:'1997年', place:'大分県中津市',
      wiki:{ja:'風の丘葬斎場', en:'Kaze-no-Oka Crematorium'},
      note:'古墳の隣の芝生の丘に、コールテン鋼とコンクリートの箱を静かに沈める。' },
    { id:'maki-sfc', answer:'maki', level:3, image:'', title:'慶應義塾大学 湘南藤沢キャンパス', year:'1990年', place:'神奈川県藤沢市',
      wiki:{ja:'慶應義塾大学湘南藤沢キャンパス', en:'Keio University Shonan Fujisawa Campus'},
      note:'中央に軸線を通し、アルミとガラスの棟を左右に配した「大学のための都市」。' },
    { id:'maki-izumo', answer:'maki', level:3, image:'', title:'島根県立古代出雲歴史博物館', year:'2007年', place:'島根県出雲市',
      wiki:{ja:'島根県立古代出雲歴史博物館', en:'Shimane Museum of Ancient Izumo'},
      note:'出雲大社の隣。コールテン鋼の長大な壁と、水盤に映る水平な庇。' },
    { id:'maki-agakhan', answer:'maki', level:3, image:'', title:'アガ・カーン博物館', year:'2014年', place:'カナダ・トロント',
      wiki:{ja:'', en:'Aga Khan Museum'},
      note:'白い花崗岩の箱に幾何学模様の窓を穿ち、中央に光の中庭を抱く。' },
    { id:'maki-medialab', answer:'maki', level:3, image:'', title:'MITメディアラボ新棟', year:'2009年', place:'アメリカ・ケンブリッジ',
      wiki:{ja:'', en:'MIT Media Lab'},
      note:'研究室を大きな吹き抜けで縦につなぎ、互いの活動が見えるガラスの箱にした。' },

    // ── 丹下健三 ──────────────────────────────────────
    { id:'tange-yoyogi', answer:'tange', level:1, image:'', title:'国立代々木競技場', year:'1964年', place:'東京都渋谷区',
      wiki:{ja:'国立代々木競技場', en:'Yoyogi National Gymnasium'},
      note:'吊り屋根構造による貝殻状のシルエット。構造と造形を一体で解いた。' },
    { id:'tange-tocho', answer:'tange', level:1, image:'', title:'東京都庁舎', year:'1991年', place:'東京都新宿区',
      wiki:{ja:'東京都庁舎', en:'Tokyo Metropolitan Government Building'},
      note:'第一本庁舎は高さ243m、頂部で2つに分かれる。外装割付はゴシック大聖堂の引用とも。' },
    { id:'tange-hiroshima', answer:'tange', level:1, image:'', title:'広島平和記念資料館', year:'1955年', place:'広島県広島市',
      wiki:{ja:'広島平和記念資料館', en:'Hiroshima Peace Memorial Museum'},
      note:'ピロティで持ち上げた本館の下を抜けると、慰霊碑と原爆ドームが一直線に並ぶ。' },
    { id:'tange-cathedral', answer:'tange', level:2, image:'', title:'東京カテドラル聖マリア大聖堂', year:'1964年', place:'東京都文京区',
      wiki:{ja:'東京カテドラル聖マリア大聖堂', en:'St. Mary’s Cathedral, Tokyo'},
      note:'8枚のHPシェルが立ち上がり、平面は十字、見上げると天窓が十字に光る。' },
    { id:'tange-kagawa', answer:'tange', level:2, image:'', title:'香川県庁舎 東館', year:'1958年', place:'香川県高松市',
      wiki:{ja:'香川県庁舎', en:'Kagawa Prefectural Government Office'},
      note:'細い梁の小口を積み重ね、五重塔の組物をコンクリートに翻訳した。' },
    { id:'tange-yamanashi', answer:'tange', level:3, image:'', title:'山梨文化会館', year:'1966年', place:'山梨県甲府市',
      wiki:{ja:'山梨文化会館', en:'Yamanashi Press and Broadcasting Center'},
      note:'16本の円筒コアを立て、その間に床を架け渡す。増築を前提としたメタボリズムの実作。' },
    { id:'tange-sogetsu', answer:'tange', level:3, image:'', title:'草月会館', year:'1977年', place:'東京都港区',
      wiki:{ja:'草月会館', en:'Sogetsu Kaikan'},
      note:'皇居の緑を映す濃緑のミラーガラス。1階にイサム・ノグチの石の広場を抱く。' },
    { id:'tange-imabari', answer:'tange', level:3, image:'', title:'今治市公会堂', year:'1958年', place:'愛媛県今治市',
      wiki:{ja:'今治市公会堂', en:'Imabari City Public Hall'},
      note:'扇形の平面に、鋭く尖った打放しの柱が林立する。市庁舎と一体の初期作。' },
    { id:'tange-kurashiki', answer:'tange', level:3, image:'', title:'倉敷市立美術館（旧倉敷市庁舎）', year:'1960年', place:'岡山県倉敷市',
      wiki:{ja:'倉敷市立美術館', en:'Kurashiki City Art Museum'},
      note:'太い梁を大胆に積み上げた重厚な打放し。校倉造の力強さを引き写した。' },
    { id:'tange-fujitv', answer:'tange', level:2, image:'', title:'フジテレビ本社ビル', year:'1996年', place:'東京都港区',
      wiki:{ja:'フジテレビ本社ビル', en:'Fuji Television'},
      note:'2棟を回廊で格子状に結び、その交点に直径32mの球体展望室を吊る。' },
    { id:'tange-parktower', answer:'tange', level:3, image:'', title:'新宿パークタワー', year:'1994年', place:'東京都新宿区',
      wiki:{ja:'新宿パークタワー', en:'Shinjuku Park Tower'},
      note:'高さの違う3棟を階段状に並べ、頂部をガラスの切妻で揃える。' },
    { id:'tange-unu', answer:'tange', level:3, image:'', title:'国際連合大学本部ビル', year:'1992年', place:'東京都渋谷区',
      wiki:{ja:'国際連合大学', en:'United Nations University'},
      note:'青山通りに面した鋭い三角形の切妻。左右非対称のシャープな石の壁。' },

    // ── 黒川紀章 ──────────────────────────────────────
    { id:'kurokawa-nakagin', answer:'kurokawa', level:1, image:'', title:'中銀カプセルタワービル', year:'1972年', place:'東京都中央区',
      wiki:{ja:'中銀カプセルタワービル', en:'Nakagin Capsule Tower'},
      note:'2本のコアに140個の住戸カプセルをボルト留め。メタボリズムを実現した唯一の集合住宅。' },
    { id:'kurokawa-shinbi', answer:'kurokawa', level:1, image:'', title:'国立新美術館', year:'2007年', place:'東京都港区',
      wiki:{ja:'国立新美術館', en:'The National Art Center, Tokyo'},
      note:'全長160mの波打つガラスカーテンウォール。内部に2つの巨大な逆円錐が立つ。' },
    { id:'kurokawa-hiroshima', answer:'kurokawa', level:2, image:'', title:'広島市現代美術館', year:'1989年', place:'広島県広島市',
      wiki:{ja:'広島市現代美術館', en:'Hiroshima City Museum of Contemporary Art'},
      note:'比治山の丘上。瓦や石やアルミを段階的に切り替え、蔵の並ぶ集落のように構成する。' },
    { id:'kurokawa-saitama', answer:'kurokawa', level:3, image:'', title:'埼玉県立近代美術館', year:'1982年', place:'埼玉県さいたま市',
      wiki:{ja:'埼玉県立近代美術館', en:'The Museum of Modern Art, Saitama'},
      note:'公園側の正面を格子（グリッド）のフレームで覆い、建物の輪郭をわざと曖昧にする。' },
    { id:'kurokawa-nagoya', answer:'kurokawa', level:3, image:'', title:'名古屋市美術館', year:'1988年', place:'愛知県名古屋市',
      wiki:{ja:'名古屋市美術館', en:'Nagoya City Art Museum'},
      note:'白川公園の緑に半分沈む。石・タイル・ガラスと、日本瓦の庇を意識的に混在させた。' },
    { id:'kurokawa-wakayama', answer:'kurokawa', level:3, image:'', title:'和歌山県立近代美術館', year:'1994年', place:'和歌山県和歌山市',
      wiki:{ja:'和歌山県立近代美術館', en:'The Museum of Modern Art, Wakayama'},
      note:'和歌山城の隣。灯籠を思わせる深い庇を何層にも重ねた、和風色の濃い作。' },
    { id:'kurokawa-fukui', answer:'kurokawa', level:3, image:'', title:'福井市美術館', year:'1996年', place:'福井県福井市',
      wiki:{ja:'福井市美術館', en:'Fukui City Art Museum'},
      note:'水盤に浮かぶガラスの円錐と、それを受け止める曲面の壁。' },
    { id:'kurokawa-ehime', answer:'kurokawa', level:3, image:'', title:'愛媛県総合科学博物館', year:'1994年', place:'愛媛県新居浜市',
      wiki:{ja:'愛媛県総合科学博物館', en:'Ehime Prefectural Science Museum'},
      note:'球（プラネタリウム）・円錐・直方体という原初的な立体を並べ置く。' },
    { id:'kurokawa-oita', answer:'kurokawa', level:3, image:'', title:'大分市美術館', year:'1998年', place:'大分県大分市',
      wiki:{ja:'大分市美術館', en:'Oita City Art Museum'},
      note:'上野の森の斜面に沿う。ガラスのアトリウムを軸に、展示棟が枝分かれする。' },
    { id:'kurokawa-bunraku', answer:'kurokawa', level:3, image:'', title:'国立文楽劇場', year:'1984年', place:'大阪府大阪市',
      wiki:{ja:'国立文楽劇場', en:'National Bunraku Theatre'},
      note:'白壁と黒い庇で蔵を思わせる正面。屋根の反りに数寄屋の手つきが残る。' },
    { id:'kurokawa-grandcube', answer:'kurokawa', level:3, image:'', title:'大阪国際会議場（グランキューブ大阪）', year:'2000年', place:'大阪府大阪市',
      wiki:{ja:'大阪国際会議場', en:'Osaka International Convention Center'},
      note:'アルミの巨大な曲面屋根が箱の上に浮く。中之島の川面に向かって開く。' },
    { id:'kurokawa-klia', answer:'kurokawa', level:2, image:'', title:'クアラルンプール国際空港', year:'1998年', place:'マレーシア・セパン',
      wiki:{ja:'クアラルンプール国際空港', en:'Kuala Lumpur International Airport'},
      note:'放物線を描く傘状の屋根が連続する。サテライト中央に熱帯雨林をそのまま取り込んだ。' },

    // ── 藤森照信 ──────────────────────────────────────
    { id:'fujimori-jinchokan', answer:'fujimori', level:2, image:'', title:'神長官守矢史料館', year:'1991年', place:'長野県茅野市',
      wiki:{ja:'神長官守矢史料館', en:'Jinchokan Moriya Historical Museum'},
      note:'建築史家からの転身第一作。土壁と鉄平石の屋根を貫いて4本の柱が突き出す。' },
    { id:'fujimori-takasugian', answer:'fujimori', level:2, image:'', title:'高過庵', year:'2004年', place:'長野県茅野市',
      wiki:{ja:'高過庵', en:'Takasugi-an'},
      note:'2本の栗の木の上、地上6mに載る茶室。梯子を登らないと入れない。' },
    { id:'fujimori-lacollina', answer:'fujimori', level:2, image:'', title:'ラ コリーナ近江八幡 草屋根', year:'2015年', place:'滋賀県近江八幡市',
      wiki:{ja:'ラ コリーナ近江八幡', en:'La Collina Omi-Hachiman'},
      note:'屋根一面を芝で覆い、丘そのものが建物になる。炭を焼いた黒い柱が林立する。' },
    { id:'fujimori-mosaic', answer:'fujimori', level:2, image:'', title:'多治見市モザイクタイルミュージアム', year:'2016年', place:'岐阜県多治見市',
      wiki:{ja:'多治見市モザイクタイルミュージアム', en:'Tajimi City Mosaic Tile Museum'},
      note:'タイルの土を採った山を模した土色の壁に、無数のタイル片が埋め込まれる。' },
    { id:'fujimori-akino', answer:'fujimori', level:3, image:'', title:'秋野不矩美術館', year:'1998年', place:'静岡県浜松市',
      wiki:{ja:'秋野不矩美術館', en:'Akino Fuku Museum'},
      note:'漆喰の白い壁と手斧仕上げの柱。展示室は籐むしろ敷きで、靴を脱いで観る。' },
    { id:'fujimori-ramune', answer:'fujimori', level:3, image:'', title:'ラムネ温泉館', year:'2005年', place:'大分県竹田市',
      wiki:{ja:'長湯温泉', en:'Nagayu Onsen'},
      note:'白黒の横縞に塗り分けた壁から、松を植えた三角屋根の塔が突き出す。' },
    { id:'fujimori-tanpopo', answer:'fujimori', level:3, image:'', title:'タンポポハウス', year:'1995年', place:'東京都国分寺市',
      wiki:{ja:'', en:'Dandelion House'},
      note:'自邸。鉄平石を貼った壁と屋根の目地からタンポポを生やした。' },
    { id:'fujimori-nira', answer:'fujimori', level:3, image:'', title:'ニラハウス', year:'1997年', place:'東京都町田市',
      wiki:{ja:'', en:'Nira House'},
      note:'赤瀬川原平の自邸。銅板葺きの屋根の上にニラを一列に植えた。' },
    { id:'fujimori-doronoki', answer:'fujimori', level:3, image:'', title:'空飛ぶ泥舟', year:'2010年', place:'長野県茅野市',
      wiki:{ja:'空飛ぶ泥舟', en:'Flying Mud Boat'},
      note:'ワイヤーで宙吊りにされた舟形の茶室。高過庵と並んで諏訪の風景に浮かぶ。' },
    { id:'fujimori-hikuian', answer:'fujimori', level:3, image:'', title:'低過庵', year:'2017年', place:'長野県茅野市',
      wiki:{ja:'低過庵', en:'Hikui-an'},
      note:'高過庵の隣に半分埋めた竪穴式の茶室。屋根がレールで横にずれて開く。' },
    { id:'fujimori-kumamoto', answer:'fujimori', level:3, image:'', title:'熊本県立農業大学校 学生寮', year:'2000年', place:'熊本県合志市',
      wiki:{ja:'', en:'Kumamoto Prefectural Agricultural College Dormitory'},
      note:'くまもとアートポリスの一作。焼杉の外壁に、草を生やした煙突が並ぶ。' },

    // ── フランク・ロイド・ライト ──────────────────────
    { id:'wright-falling', answer:'wright', level:1, image:'', title:'落水荘（カウフマン邸）', year:'1936年', place:'アメリカ・ペンシルベニア州',
      wiki:{ja:'落水荘', en:'Fallingwater'},
      note:'滝の上にキャンチレバーのテラスを何層も張り出す。有機的建築の代表作。' },
    { id:'wright-guggenheim', answer:'wright', level:1, image:'', title:'ソロモン・R・グッゲンハイム美術館', year:'1959年', place:'アメリカ・ニューヨーク',
      wiki:{ja:'ソロモン・R・グッゲンハイム美術館', en:'Solomon R. Guggenheim Museum'},
      note:'上に向かって広がる逆円錐。途切れない螺旋スロープが展示室そのものになる。' },
    { id:'wright-myonichikan', answer:'wright', level:2, image:'', title:'自由学園明日館', year:'1921年', place:'東京都豊島区',
      wiki:{ja:'自由学園明日館', en:'Jiyu Gakuen Girls’ School'},
      note:'中央棟を低く抑え、左右に翼を広げるプレーリースタイル。幾何学的な窓割りが目印。' },
    { id:'wright-robie', answer:'wright', level:2, image:'', title:'ロビー邸', year:'1910年', place:'アメリカ・シカゴ',
      wiki:{ja:'ロビー邸', en:'Robie House'},
      note:'極端に長く伸びた水平の庇。プレーリースタイルの完成形とされる。' },
    { id:'wright-imperial', answer:'wright', level:2, image:'', title:'旧帝国ホテル 中央玄関', year:'1923年', place:'愛知県犬山市（博物館明治村）',
      wiki:{ja:'帝国ホテル', en:'Imperial Hotel, Tokyo'},
      note:'大谷石とスクラッチタイルを彫り込んだ幾何学装飾。関東大震災の当日に落成した。' },
    { id:'wright-yodoko', answer:'wright', level:3, image:'', title:'ヨドコウ迎賓館（旧山邑家住宅）', year:'1924年', place:'兵庫県芦屋市',
      wiki:{ja:'ヨドコウ迎賓館', en:'Yamamura House'},
      note:'六甲の急斜面に4層を段状に重ねる。大谷石の飾りと銅板の庇が水平に伸びる。' },
    { id:'wright-taliesinwest', answer:'wright', level:3, image:'', title:'タリアセン・ウェスト', year:'1937年', place:'アメリカ・アリゾナ州',
      wiki:{ja:'タリアセン・ウェスト', en:'Taliesin West'},
      note:'砂漠の石をコンクリートで固めた壁に、木とキャンバスの傾いた屋根を架ける。' },
    { id:'wright-johnson', answer:'wright', level:3, image:'', title:'ジョンソン・ワックス本社ビル', year:'1939年', place:'アメリカ・ウィスコンシン州',
      wiki:{ja:'', en:'Johnson Wax Headquarters'},
      note:'上へ広がる「睡蓮」型の細い柱が林立し、柱の間をガラス管の天窓が埋める。' },
    { id:'wright-unity', answer:'wright', level:3, image:'', title:'ユニティ・テンプル', year:'1908年', place:'アメリカ・オークパーク',
      wiki:{ja:'ユニティ・テンプル', en:'Unity Temple'},
      note:'打放しコンクリートを本格的に使った最初期の建築。外に窓を開けず天窓から採光する。' },
    { id:'wright-marin', answer:'wright', level:3, image:'', title:'マリン郡庁舎', year:'1962年', place:'アメリカ・カリフォルニア州',
      wiki:{ja:'マリン郡庁舎', en:'Marin County Civic Center'},
      note:'最晩年の遺作。丘と丘の間に青い屋根の長大なアーチの橋を架け渡す。' },
    { id:'wright-hollyhock', answer:'wright', level:3, image:'', title:'ホリーホック・ハウス', year:'1921年', place:'アメリカ・ロサンゼルス',
      wiki:{ja:'', en:'Hollyhock House'},
      note:'マヤの神殿を思わせる傾いた壁。タチアオイ（ホリーホック）を抽象化した装飾が巡る。' },
    { id:'wright-price', answer:'wright', level:3, image:'', title:'プライス・タワー', year:'1956年', place:'アメリカ・オクラホマ州',
      wiki:{ja:'', en:'Price Tower'},
      note:'唯一実現した高層建築。銅の日除けが風車状の平面から幾重にも突き出す。' },

    // ── ル・コルビュジエ ──────────────────────────────
    { id:'corbu-savoye', answer:'corbu', level:1, image:'', title:'サヴォア邸', year:'1931年', place:'フランス・ポワシー',
      wiki:{ja:'サヴォア邸', en:'Villa Savoye'},
      note:'ピロティ・屋上庭園・自由な平面・自由な立面・水平連続窓——近代建築の五原則の完成形。' },
    { id:'corbu-ronchamp', answer:'corbu', level:1, image:'', title:'ロンシャンの礼拝堂', year:'1955年', place:'フランス・ロンシャン',
      wiki:{ja:'ロンシャンの礼拝堂', en:'Notre-Dame du Haut'},
      note:'反り上がる分厚い屋根と、深く穿たれた不規則な窓。彫塑的表現への転回点。' },
    { id:'corbu-nmwa', answer:'corbu', level:1, image:'', title:'国立西洋美術館', year:'1959年', place:'東京都台東区',
      wiki:{ja:'国立西洋美術館', en:'National Museum of Western Art'},
      note:'「無限成長美術館」の構想を実現した唯一の作例。日本にある唯一の彼の建築。' },
    { id:'corbu-unite', answer:'corbu', level:2, image:'', title:'ユニテ・ダビタシオン', year:'1952年', place:'フランス・マルセイユ',
      wiki:{ja:'ユニテ・ダビタシオン', en:'Unité d’habitation'},
      note:'337戸を1棟に収めた「垂直の田園都市」。屋上に保育園とランニングトラックを載せる。' },
    { id:'corbu-tourette', answer:'corbu', level:2, image:'', title:'ラ・トゥーレット修道院', year:'1960年', place:'フランス・エヴー',
      wiki:{ja:'ラ・トゥーレット修道院', en:'Sainte Marie de La Tourette'},
      note:'斜面に脚を突いて水平に浮く僧房。廊下の「光の大砲」が礼拝堂に色光を落とす。' },
    { id:'corbu-chandigarh', answer:'corbu', level:3, image:'', title:'チャンディーガル 議事堂', year:'1962年', place:'インド・チャンディーガル',
      wiki:{ja:'チャンディーガル', en:'Palace of Assembly, Chandigarh'},
      note:'冷却塔のような双曲面の議場が屋根を突き破る。前面に反り返った巨大な庇。' },
    { id:'corbu-laroche', answer:'corbu', level:3, image:'', title:'ラ・ロッシュ＝ジャンヌレ邸', year:'1925年', place:'フランス・パリ',
      wiki:{ja:'ラ・ロッシュ＝ジャンヌレ邸', en:'Villa La Roche'},
      note:'白い箱をピロティで浮かせた初期作。曲面のギャラリーにスロープが取り付く。' },
    { id:'corbu-cabanon', answer:'corbu', level:3, image:'', title:'カップ・マルタンの休暇小屋', year:'1952年', place:'フランス・ロクブリュヌ＝カップ＝マルタン',
      wiki:{ja:'カップ・マルタンの休暇小屋', en:'Le Cabanon'},
      note:'3.66m四方の丸太小屋。モデュロールで隅々まで寸法を決めた自身の終の住処。' },
    { id:'corbu-pavillonsuisse', answer:'corbu', level:3, image:'', title:'スイス学生会館', year:'1932年', place:'フランス・パリ',
      wiki:{ja:'スイス学生会館', en:'Pavillon Suisse'},
      note:'太い彫刻的なピロティで箱を持ち上げる。曲面の石壁が背後に取り付く。' },
    { id:'corbu-pessac', answer:'corbu', level:3, image:'', title:'ペサックの集合住宅', year:'1926年', place:'フランス・ペサック',
      wiki:{ja:'ペサックの集合住宅', en:'Quartiers Modernes Fruges'},
      note:'量産住宅の実験。立方体を並べ、面ごとに色を塗り分けて奥行きを操作した。' },
    { id:'corbu-carpenter', answer:'corbu', level:3, image:'', title:'カーペンター視覚芸術センター', year:'1963年', place:'アメリカ・ケンブリッジ',
      wiki:{ja:'', en:'Carpenter Center for the Visual Arts'},
      note:'北米で唯一の作。S字のスロープが建物を貫通し、キャンパスの通り道になる。' },
    { id:'corbu-philips', answer:'corbu', level:3, image:'', title:'フィリップス・パビリオン', year:'1958年', place:'ベルギー・ブリュッセル',
      wiki:{ja:'フィリップス・パビリオン', en:'Philips Pavilion'},
      note:'双曲放物面を組み合わせた仮設。クセナキスが形を、ヴァレーズが音楽を担った。' },
    { id:'corbu-firminy', answer:'corbu', level:3, image:'', title:'サン・ピエール教会', year:'2006年', place:'フランス・フィルミニ',
      wiki:{ja:'', en:'Saint-Pierre, Firminy'},
      note:'没後40年余を経て完成した円錐。壁の小孔がオリオン座の形に光を落とす。' },

    // ── ミース・ファン・デル・ローエ ──────────────────
    { id:'mies-barcelona', answer:'mies', level:1, image:'', title:'バルセロナ・パビリオン', year:'1929年', place:'スペイン・バルセロナ',
      wiki:{ja:'バルセロナ・パビリオン', en:'Barcelona Pavilion'},
      note:'薄い屋根と独立した壁だけ。オニキスや大理石の面が空間を仕切らずに流れをつくる。' },
    { id:'mies-farnsworth', answer:'mies', level:1, image:'', title:'ファンズワース邸', year:'1951年', place:'アメリカ・イリノイ州',
      wiki:{ja:'ファンズワース邸', en:'Farnsworth House'},
      note:'白い鉄骨で地面から浮かせた全面ガラスの一室空間。「Less is more」の極点。' },
    { id:'mies-seagram', answer:'mies', level:1, image:'', title:'シーグラム・ビルディング', year:'1958年', place:'アメリカ・ニューヨーク',
      wiki:{ja:'シーグラム・ビルディング', en:'Seagram Building'},
      note:'ブロンズ色のカーテンウォールとH形鋼のマリオン。前面のプラザが以後の規範に。' },
    { id:'mies-tugendhat', answer:'mies', level:2, image:'', title:'トゥーゲントハット邸', year:'1930年', place:'チェコ・ブルノ',
      wiki:{ja:'トゥーゲントハット邸', en:'Villa Tugendhat'},
      note:'十字断面の鍍金柱と、床に沈む大ガラス。オニキスの壁が居間を緩く分ける。' },
    { id:'mies-neue', answer:'mies', level:2, image:'', title:'新ナショナルギャラリー', year:'1968年', place:'ドイツ・ベルリン',
      wiki:{ja:'新ナショナルギャラリー', en:'Neue Nationalgalerie'},
      note:'8本の柱だけで支えた65m角の鉄の屋根。遺作となったガラスの神殿。' },
    { id:'mies-crown', answer:'mies', level:3, image:'', title:'クラウンホール', year:'1956年', place:'アメリカ・シカゴ',
      wiki:{ja:'クラウンホール', en:'S. R. Crown Hall'},
      note:'IIT建築学部棟。4本の鉄骨梁で屋根を吊り、内部を完全な無柱の一室にした。' },
    { id:'mies-lakeshore', answer:'mies', level:3, image:'', title:'レイクショア・ドライブ・アパートメント', year:'1951年', place:'アメリカ・シカゴ',
      wiki:{ja:'', en:'860–880 Lake Shore Drive Apartments'},
      note:'2棟を直交させて配置。鉄とガラスの高層住宅の原型となった。' },
    { id:'mies-toronto', answer:'mies', level:3, image:'', title:'トロント・ドミニオン・センター', year:'1969年', place:'カナダ・トロント',
      wiki:{ja:'トロント・ドミニオン・センター', en:'Toronto-Dominion Centre'},
      note:'黒い鉄とブロンズガラスの塔群。低層の銀行営業室だけが平屋で自立する。' },
    { id:'mies-krefeld', answer:'mies', level:3, image:'', title:'ハウス・ランゲとハウス・エスタース', year:'1930年', place:'ドイツ・クレフェルト',
      wiki:{ja:'', en:'Haus Lange and Haus Esters'},
      note:'珍しい煉瓦造の住宅。直角に組んだ壁が庭へ向かって開いていく。' },
    { id:'mies-weissenhof', answer:'mies', level:3, image:'', title:'ヴァイセンホーフ・ジードルング', year:'1927年', place:'ドイツ・シュトゥットガルト',
      wiki:{ja:'ヴァイセンホーフ・ジードルング', en:'Weissenhof Estate'},
      note:'自ら全体計画を率いた実験住宅地。彼の担当棟は鉄骨で間仕切りを自由にした。' },
    { id:'mies-federal', answer:'mies', level:3, image:'', title:'シカゴ連邦センター', year:'1974年', place:'アメリカ・シカゴ',
      wiki:{ja:'', en:'Chicago Federal Center'},
      note:'黒い塔2棟と平屋の郵便局で広場を囲む。中央にコルダーの赤い彫刻が立つ。' },

    // ── アントニ・ガウディ ────────────────────────────
    { id:'gaudi-sagrada', answer:'gaudi', level:1, image:'', title:'サグラダ・ファミリア', year:'1882年–', place:'スペイン・バルセロナ',
      wiki:{ja:'サグラダ・ファミリア', en:'Sagrada Família'},
      note:'逆さ吊り実験から導いた斜めの柱が森のように枝分かれする。いまも建設が続く。' },
    { id:'gaudi-mila', answer:'gaudi', level:1, image:'', title:'カサ・ミラ', year:'1912年', place:'スペイン・バルセロナ',
      wiki:{ja:'カサ・ミラ', en:'Casa Milà'},
      note:'直線を一切使わない波打つ石の外壁。屋上に兜のような煙突群が立つ。' },
    { id:'gaudi-batllo', answer:'gaudi', level:1, image:'', title:'カサ・バトリョ', year:'1906年', place:'スペイン・バルセロナ',
      wiki:{ja:'カサ・バトリョ', en:'Casa Batlló'},
      note:'骨のような柱とタイルの鱗。うろこ状の屋根は竜の背とも言われる。' },
    { id:'gaudi-guellpark', answer:'gaudi', level:1, image:'', title:'グエル公園', year:'1914年', place:'スペイン・バルセロナ',
      wiki:{ja:'グエル公園', en:'Park Güell'},
      note:'割れタイルのモザイク（トレンカディス）で覆われた蛇行ベンチと、傾いた列柱の回廊。' },
    { id:'gaudi-vicens', answer:'gaudi', level:2, image:'', title:'カサ・ビセンス', year:'1885年', place:'スペイン・バルセロナ',
      wiki:{ja:'カサ・ビセンス', en:'Casa Vicens'},
      note:'処女作。緑と白の市松タイルとマリーゴールドの文様。ムデハル様式の色が濃い。' },
    { id:'gaudi-guellpalace', answer:'gaudi', level:2, image:'', title:'グエル邸', year:'1890年', place:'スペイン・バルセロナ',
      wiki:{ja:'グエル邸', en:'Palau Güell'},
      note:'パトロンの邸宅。放物線アーチの門と、屋上の色とりどりの煙突。' },
    { id:'gaudi-colonia', answer:'gaudi', level:3, image:'', title:'コロニア・グエル教会 地下聖堂', year:'1914年', place:'スペイン・サンタ・コロマ・ダ・サルバリョー',
      wiki:{ja:'コロニア・グエル', en:'Church of Colònia Güell'},
      note:'逆さ吊り模型で構造を決めた実験場。傾いた玄武岩と煉瓦の柱が斜めに立つ。' },
    { id:'gaudi-capricho', answer:'gaudi', level:3, image:'', title:'エル・カプリチョ', year:'1885年', place:'スペイン・コミージャス',
      wiki:{ja:'エル・カプリチョ', en:'El Capricho'},
      note:'バルセロナ外の初期作。ひまわりのタイルの帯が巡り、細い塔がミナレットのように立つ。' },
    { id:'gaudi-calvet', answer:'gaudi', level:3, image:'', title:'カサ・カルベット', year:'1900年', place:'スペイン・バルセロナ',
      wiki:{ja:'カサ・カルベット', en:'Casa Calvet'},
      note:'もっとも大人しい作でバルセロナ市の建築賞を受賞。バロック風の石の正面。' },
    { id:'gaudi-bellesguard', answer:'gaudi', level:3, image:'', title:'ベリェスグアール', year:'1909年', place:'スペイン・バルセロナ',
      wiki:{ja:'ベリェスグアール', en:'Bellesguard'},
      note:'中世の城跡に建つ。急勾配の切妻と細い塔で、ゴシックの城を思わせる異色作。' },
    { id:'gaudi-astorga', answer:'gaudi', level:3, image:'', title:'アストルガ司教館', year:'1893年', place:'スペイン・アストルガ',
      wiki:{ja:'アストルガ司教館', en:'Episcopal Palace of Astorga'},
      note:'白い花崗岩の城。4本の円塔と堀に囲まれ、内部は肋骨のようなアーチが交差する。' },
    { id:'gaudi-botines', answer:'gaudi', level:3, image:'', title:'カサ・ボティネス', year:'1892年', place:'スペイン・レオン',
      wiki:{ja:'カサ・ボティネス', en:'Casa Botines'},
      note:'灰色の石を粗く積んだネオゴシック。四隅に円塔、玄関上に聖ジョルディの像。' },
    { id:'gaudi-pedralbes', answer:'gaudi', level:3, image:'', title:'グエル別邸の竜の門', year:'1887年', place:'スペイン・バルセロナ',
      wiki:{ja:'グエル別邸', en:'Güell Pavilions'},
      note:'鉄で作られた翼を広げる竜の門扉。庭園の門番小屋と厩舎が残る。' },
  ],
};
